### ISSUE TITLE
could not determine kind of name for C._argc

### ISSUE THREAD

**Issue by josephspurrier** [matwachich/iup#1]
I downloaded the following static libraries (https://sourceforge.net/projects/iup/files/3.18/Windows%20Libraries/Static/) and tried them both with the same error:
- iup-3.18_Win64_vc14_lib.zip
- iup-3.18_Win64_mingw4_lib.zip

I still receive this error when I try to compile the hello world code: could not determine kind of name for C._argc

![error](https://cloud.githubusercontent.com/assets/2394539/14212812/ad6f610e-f802-11e5-9062-0270a2e576c6.PNG)

I get the same error building outside LiteIDE.

Here are the static libraries. I'm on Windows 10 building using Go 1.6 64.

![lib](https://cloud.githubusercontent.com/assets/2394539/14212725/3c194bf0-f802-11e5-9ad1-409c7024e78c.PNG)

**Comment by matwachich** [comment]
What is your C compiler? _argc is a MinGW global variable that I pass to C.IupOpen (see iup.go line 64).
Gonna remove it now since it makes problemes (and since it is not used in Windows).

Please continue posting issues while testing with x64 compiler. I only test with x86.

PS: the directory structure is good. But don't use visual C++ libraries since CGO doesn't work with them. iup-3.18_Win64_mingw4_lib.zip or iup-3.18_Win32_mingw4_lib.zip is what you need.

**Comment by josephspurrier** [comment]
This error is gone now that I'm using the new files you committed about an hour ago.
